Drugie_życie_gabarytów/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')),
    path('accounts/', include('accounts.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/urls.py
from django.urls import path

from accounts import views

app_name = 'accounts'

urlpatterns = [

    path('register/', views.register_request, name='register'),
    path('login/', views.login_request, name='login'),
    # path('user_view/', views.user_view, name='user_view'),
    path('logout/', views.logout_request, name='logout'),

]

main_app/urls.py
from django.urls import path

from main_app import views

app_name = 'main_app'

urlpatterns = [
    path('', views.home, name='home'),
    path('about_us/', views.about_us, name='about_us'),

    # PRODUCT
    path('auctions/', views.auction_view, name='auctions'),
    path('<int:pk>/', views.product_detail_view, name='product_detail_view'),
    path('add/', views.add_product, name='add'),
    path('search/', views.search_by_name, name='search'),

    # USER
    path('user_products/', views.users_products, name='user_products'),
    path('update_product/<int:pk>/', views.update_product, name='update_product'),
    path('delete/<int:pk>/', views.delete_product, name='delete_product'),

    # CART
    path('cart/<int:pk>/', views.add_to_shopping_cart, name='add_to_shopping_cart'),
    path('cart_view/', views.cart_view, name='cart_view'),
    path('order_complete/', views.buy_now, name='order_complete'),
    path('remove/<int:pk>/', views.cart_remove, name='cart_remove'),
    path('update_cart/<int:pk>/', views.update_cart, name='update_cart'),

    #ORDER_VIEW
    path('orders/', views.orders, name='orders'),

]

main_app/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.core.validators import MinValueValidator

class User(AbstractUser):
    pass


class Product(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField()
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    photo = models.ImageField(null=True, blank=True, upload_to='images/')
    category = models.ForeignKey('Category', on_delete=models.CASCADE)
    quantity = models.IntegerField(default=1, validators=[MinValueValidator(1)])
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f' {self.name}, {self.price}'

    @staticmethod
    def get_all_products_by_category_id(category_id):
        if category_id:
            return Product.objects.filter (category=category_id)
        else:
            return Product.objects.all()


class Category(models.Model):
    parent_category_id = models.ForeignKey('Category', on_delete=models.CASCADE, null=True, blank=True)
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name

    @staticmethod
    def get_all_categories():
        return Category.objects.all()


class ShoppingCart(models.Model):
    user_id = models.ForeignKey('User', on_delete=models.CASCADE)

    def __str__(self):
        return str(self.user_id)


class ShoppingCartItem(models.Model):
    cart_id = models.ForeignKey('ShoppingCart', on_delete=models.CASCADE)
    product_item = models.ForeignKey('Product', on_delete=models.CASCADE)
    qty = models.IntegerField(default=1)

    def __str__(self):
        return str(self.product_item)


class Order(models.Model):
    customer = models.ForeignKey('User', blank=True, null=True, on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return str(self.customer)


class OrderItem(models.Model):
    order = models.ForeignKey('Order', on_delete=models.CASCADE)
    product = models.CharField(max_length=100)
    quantity = models.IntegerField(default=1)

main_app/forms.py
from django import forms
from .models import Product


class AddProduct(forms.ModelForm):
    class Meta:
        model = Product
        fields = [
            'name',
            'description',
            'price',
            'photo',
            'quantity',
            'category',
        ]

main_app/views.py
from django.shortcuts import render, redirect, get_object_or_404
from main_app.models import Product, ShoppingCart, ShoppingCartItem, Category, Order, OrderItem
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from .forms import AddProduct
from decimal import Decimal
from django.core.exceptions import ObjectDoesNotExist


def home(request):
    return render(request,
                  'main_app/home.html')


def auction_view(request):
    categories = Category.get_all_categories()
    category_id = request.GET.get('category')
    if category_id:
        products = Product.get_all_products_by_category_id(category_id)
    else:
        products = Product.objects.all()

    return render(request, 'main_app/product_list.html', context={'products': products, 'categories': categories})


def product_detail_view(request, pk):
    product = get_object_or_404(Product, id=pk)
    if product.quantity == 0:
        messages.info(request, 'Sorry, this product is out of stock')
    return render(request, 'main_app/product_detail.html', context={'product': product})


@login_required(login_url='accounts:login')
def add_product(request):

    form = AddProduct(request.POST or None, request.FILES)
    if form.is_valid():
        form = form.save(commit=False)
        form.user = request.user
        form.save()
        return redirect('main_app:auctions')
    return render(request, 'main_app/add_product.html', context={'form': form})


def get_user_shopping_cart(request):
    if request.user.is_authenticated and not request.user.is_anonymous:
        try:
            cart = ShoppingCart.objects.get(user_id=request.user)
            cart.save()

        except ShoppingCart.DoesNotExist:
            cart = ShoppingCart(user_id=request.user)
            cart.save()

        return cart


@login_required
def add_to_shopping_cart(request, pk):
    cart = get_user_shopping_cart(request)
    product = get_object_or_404(Product, id=pk)
    show_cart = ShoppingCartItem.objects.filter(cart_id=cart)
    try:
        cart_item = ShoppingCartItem.objects.get(product_item=product, cart_id=cart)
        if cart_item.qty < cart_item.product_item.quantity:
            cart_item.product_item.quantity -= 1
            cart_item.qty += 1
        cart_item.product_item.save()
        cart_item.save()

    except ShoppingCartItem.DoesNotExist:
        cart_item = ShoppingCartItem.objects.create(product_item=product, cart_id=cart)
        cart_item.product_item.quantity -= 1
        cart_item.product_item.save()
        cart_item.save()

    context = {'cart': cart, 'product': product, 'cart_item': cart_item, 'show_cart': show_cart}
    return render(request, 'main_app/shopping_cart.html', context=context)


@login_required
def cart_view(request):
    cart = get_user_shopping_cart(request)
    show_cart = ShoppingCartItem.objects.filter(cart_id=cart)
    order_total = Decimal(0.0)
    buy = buy_now(request)
    total_quantity = 0
    if buy:
        return render(request, 'main_app/order_complete.html', context={'show_cart': show_cart})

    for item in show_cart:
        order_total += item.product_item.price * item.qty

    for quantity in show_cart:
        total_quantity += quantity.qty

    return render(request, 'main_app/cart_view.html',
                  context={'show_cart': show_cart, 'order_total': order_total, 'total_quantity': total_quantity})


@login_required
def users_products(request):

    product = Product.objects.filter(user=request.user)
    return render(request, 'main_app/user_products.html', context={'product': product})


def update_product(request, pk):
    product_to_update = get_object_or_404(Product, id=pk)
    update_form = AddProduct(request.POST or None, request.FILES or None, instance=product_to_update)
    if request.method == 'GET':
        return render(request, 'main_app/update_product.html',
                      context={'update_form': update_form, 'product_to_update': product_to_update})

    if request.method == 'POST':
        if update_form.is_valid():
            update_form.save()
        else:
            messages.error(request, "You can't add negative value")
            return render(request, 'main_app/update_product.html')
        return redirect('main_app:auctions')


def buy_now(request):
    order_init = start_order(request)
    cart = get_user_shopping_cart(request)
    show_cart = ShoppingCartItem.objects.filter(cart_id=cart)
    if request.method == 'POST':
        bought = request.POST.get('buy')

        for order_item in show_cart:
            ord_itm = OrderItem.objects.create(order=order_init, product=order_item.product_item.name,
                                               quantity=order_item.qty)
            ord_itm.save()

        if bought:
            show_cart.delete()
        return redirect('main_app:order_complete')


def search_by_name(request):
    search_query = request.GET.get('q')
    results = Product.objects.filter(name__icontains=search_query)
    return render(request, 'main_app/search.html', context={'results': results})


def delete_product(request, pk):
    product = get_object_or_404(Product, id=pk)

    if request.method == 'GET':
        return render(request, 'main_app/delete_product.html', context={'product': product})

    if request.method == 'POST':
        confirm = request.POST.get('confirm')
        if confirm:
            product.delete()

    return redirect('main_app:user_products')


def cart_remove(request, pk):
    cart = get_user_shopping_cart(request)
    product = get_object_or_404(Product, id=pk)
    cart_item = ShoppingCartItem.objects.get(product_item=product, cart_id=cart)
    if cart_item.qty > 0:
        cart_item.qty -= 1
        cart_item.save()
        cart_item.product_item.quantity += 1
        cart_item.product_item.save()

    if cart_item.qty == 0:
        cart_item.delete()
    return redirect("main_app:cart_view")


def update_cart(request, pk):

    cart = get_user_shopping_cart(request)
    product = get_object_or_404(Product, id=pk)
    cart_item = ShoppingCartItem.objects.get(product_item=product, cart_id=cart)
    if cart_item.product_item.quantity > 0:
        cart_item.product_item.quantity -= 1
        cart_item.qty += 1
        cart_item.save()
        cart_item.product_item.save()
    else:
        messages.error(request, 'Sorry, there is no more this product in our auction right now')

    return redirect('main_app:cart_view')


def start_order(request):
    try:
        order = Order.objects.get(customer=request.user)
        order.save()
    except ObjectDoesNotExist:
        order = Order.objects.create(customer=request.user)
        order.save()
    return order


def orders(request):
    order = Order.objects.get(customer=request.user)
    order_view = OrderItem.objects.filter(order=order)
    return render(request, 'main_app/orders.html', context={'order_view': order_view})



def about_us(request):
    return render(request, 'main_app/about_us.html')

main_app/templates/main_app/about_us.html
{% extends 'accounts/header.html' %}

{% block title %} Product list {% endblock title %}

{% block content %}



<ol style="list-style-type: none; font-size: large">
  <h2 style="text-align: center; position: static;"> Założenia projektu:</h2>
  <li>Możliwość założenia konta użytkownika</li>
<li>Możliwość wystawiania produktów na sprzedaż</li>
<li>Możliwość dodania produktów do koszyka</li>

  <h3>Widoczne dla wszystkich:</h3>
<li>widok rejestracji</li>
<li>widok logowania</li>
<li>widok listy aukcji</li>
<li>widok detalu aukcji</li>

<h3>Widoczne dla zalogowanych użytkowników:</h3>
<li>widok formularza dodawania aukcji</li>
<li>widok formularza edycji aukcji</li>
<li>widok koszyka</li>
<li>na widoku detalu aukcji przycisk dodaj do koszyka</li>

<h3>Opcjonalnie:</h3>
<li>widok produktów po kategoriach</li>
<li>wyszukiwanie produktów po nazwie</li>
<li>tworzenie zamówienia</li>
<li>widok listy zamówionych przedmiotów</li>
</ol>



{% endblock %}

main_app/templates/main_app/add_product.html
{% extends 'accounts/header.html' %}

{% block title %} Add product{% endblock title %}


{% block content %}

<form method="POST" enctype="multipart/form-data">
  {% csrf_token %}
  {{form.as_p}}
<input type="submit" value="Add product">

</form>

{% endblock %}

main_app/templates/main_app/cart_view.html
<!DOCTYPE html>
<html lang="en">
{% extends 'accounts/header.html' %}

{% block title %} Shopping cart {% endblock title %}

{% block content %}
<body>
<div class="cart-structor">
    <h2>Products in your basket</h2>
    <div>
    {% for item in show_cart %}
        <li>PRODUCT: {{item}}</li>
        <li>QUANTITY: {{item.qty}}</li>
        <a href="{% url 'main_app:cart_remove' item.product_item.id %}"><button type="submit">Remove item</button></a>
        <a href="{% url 'main_app:update_cart' item.product_item.id%}"><button>Add +1</button></a>
    {% endfor %}
    </div>
    <div>
        <form method="POST">
          {% csrf_token %}
            <input class="buy-btn" type="submit" name="buy" value="BUY NOW">
        </form>
    </div>
    <div>
        <a href="{% url 'main_app:auctions'%}"><button class="goback-btn">Go back to shopping</button></a>
    </div>
    <!--INFO WHEN PRODUCT IS OUT OF STOCK-->
    {% for info in messages %}
    {{info}}
    {% endfor %}

    <!--WHEN BASKET IS EMPTY-->
    <div class="empty-basket">
        {% if total_quantity == 0 %}
        YOUR BASKET IS EMPTY
        {% endif %}
    </div>

    <div class="total-price">
        <h2>Total order:</h2>
        {{order_total}} USD
    </div>
</div>
</body>

{% endblock %}

main_app/templates/main_app/delete_product.html
{% extends 'accounts/header.html' %}

{% block title %} Delete product {% endblock title %}

{% block content %}

<h2> Do you want to delete this product: {{product.name}}?</h2>

<form method="POST">
  {% csrf_token %}
  <input type="submit" name="confirm" value="Delete">
  <input type="submit" name="stop" value="Cancel">

</form>

{% endblock %}

main_app/templates/main_app/home.html
{% extends 'accounts/header.html' %}

{% block title %} Main {% endblock title %}

{% block content %}

<body>

<div style="margin-bottom: 600px">
{% if user.is_authenticated %}
<h2>Hello {{user.username.capitalize}}! :)</h2>
{% endif %}
</div>

<div class="home-structor">
    <div class="home-container">
        <h2 class="home-title"> DRUGIE ŻYCIE GABARYTÓW </h2>
    </div>
    <div class="home-holder">
        <a href="{% url 'accounts:login' %}">
            <button class="login-btn" type="submit">Log in</button></a>
        <a href="{% url 'accounts:register' %}">
            <button class="signup-btn" type="submit">Sign up</button></a>
        <a href="{% url 'main_app:auctions' %}">
            <button class="auction-btn" type="submit">Auctions</button></a>
    </div>
</div>
</body>

{% endblock %}

main_app/templates/main_app/login.html
{% extends 'main_app/header.html' %}

{% block title %} Login {% endblock title %}

{% block content %}

    <div>
        <h1>Login</h1>
        <form method="POST">
            {% csrf_token %}

            <input type="text" name="username" placeholder="Username">
            <input type="password" name="password" placeholder="Password">
            <button type="submit"> Login </button>
    </div>

        {% for message in messages %}
            <p>{{message}}</p>
        {% endfor %}



{% endblock %}

main_app/templates/main_app/order_complete.html
{% extends 'accounts/header.html' %}



{% block title %} Order complete {% endblock title %}

{% block content %}

<H2> CONGRATULATIONS, YOUR ORDER IS COMPLETED</H2>

<a href="{% url 'main_app:orders' %}"><button>Order details</button></a>


{% endblock %}

main_app/templates/main_app/orders.html
{% extends 'accounts/header.html' %}

{% block title %} Order details {% endblock title %}

{% block content %}
<ol style="list-style-type: none; font-size: x-large">
{% for order in order_view %}

<li>PRODUCT: {{order.product}}</li>
<li>QUANTITY: {{order.quantity}}</li>
<li>--------------------</li>
{% endfor %}
</ol>

{% endblock %}

main_app/templates/main_app/product_detail.html
{% extends 'accounts/header.html' %}

{% block title %} Product details {% endblock title %}

{% block content %}

<div class="detail-constructor">
<p>Added by: {{product.user}}</p>
<p class="quotations"> {{product.description}}</p>
<p class="created">Created: {{product.created_at}} </p>

{% if product.photo %}
    <img src="{{product.photo.url}}" style="max-width: 10cm; max-height: 15cm">
{% endif %}



{% if product.quantity > 0 %}
<a href="{% url 'main_app:add_to_shopping_cart' product.id %}"><button type="submit">Add to cart </button></a>
{% else %}
{% for message in messages %}
<p>{{message}}</p>
{% endfor %}
{% endif %}



<a href="{% url 'main_app:auctions' %}"><button type="submit">Back to all products</button></a>
<button type="button" onclick="history.back()"> Back to search list</button>


{% endblock %}
</div>

main_app/templates/main_app/product_list.html
<!DOCTYPE html>
<html lang="en">
{% extends 'accounts/header.html' %}

{% block title %} Product list {% endblock title %}

{% block content %}
<body>
<nav>
<div class="navigation-left-box">
    <ul class="navigation-auctions-box">
        <div class="navigation-auctions">
            <div class="search-box">
            <!--WYSZUKIWANIE PO NAZWIE PRODUKTU-->
                <form action="{% url 'main_app:search' %}" role="search">
                    <label for="inp" class="search-form">
                        <input type="text" placeholder="Search" name="q" value="{{ search_query }}">
                        <span class="focus-bg"></span>
                    </label>
                    <button class="search-btn" type="submit">Submit</button>
                </form>

            </div>
            <div class="navigation-title"><a>Category</a></div>
            <!--WYSZUKIWANIE PO KATEGORIACH-->
            <div class="category" style="list-style-type: none">
                {% for category in categories %}
                <li><a href="/auctions/?category={{category.id}}">{{category.name}}</a></li>
                {% endfor %}
                {% for product in products %}
                {% endfor %}
            </div>
            <!-- LOG OUT BUTTON -->
            <a href="{% url 'accounts:logout' %}">
                <button class="logout-btn" type="submit">Log out</button></a>
        </div>
    </ul>
</div>
</nav>

<div class="auctions-structor">
    <div class="auctions-btn" style="padding: 1cm; list-style-type: none">
            <a href="{% url 'main_app:add' %}">
                <button class="auction-btn" type="submit">Add product </button></a>
            <a href="{% url 'main_app:home' %}">
                <button class="auction-btn">Back to main</button></a>
            <a href="{% url 'main_app:user_products' %}">
                <button class="auction-btn">Your products</button></a>
    </div>
        <!--LISTA WSZYSTKICH PRODUKTÓW-->
    <div class="auction-loop">
        <ul style="list-style-type: none">
        {% for product in products %}
            <div class="auction">
            <li>{{product.name}}</li>
                <div class="auction-picture">
                        <li>{% if product.photo %}
                            <img class="auction-img" src="{{product.photo.url}}">
                        </li>
                    </div>
                    <a>Quantity: {{product.quantity}}</a>
                <div class="auction-price">
                    <li>Price: {{product.price}} USD</li>
                </div>
                <a href="{% url 'main_app:product_detail_view' product.id %}">
                    <button class="details-btn">Details</button>
                </a>
            {% endif %}
            {% endfor %}
            </div>
        </ul>
    </div>
</div>

</body>
</html>
{% endblock %}

main_app/templates/main_app/search.html
{% extends 'accounts/header.html' %}

{% block title %} Searching results {% endblock title %}

{% block content %}

<ul>
{% for prod in results %}
<li style="list-style-type: none">
<a href="{% url 'main_app:product_detail_view' prod.id %}">{{prod}}</a>
</li>
{% endfor %}
</ul>


{% if not results %}

Sorry, we didn't find this product :(
<button type="button" onclick="history.back()"> Back to product list</button>

{% endif %}


{% endblock %}

main_app/templates/main_app/shopping_cart.html
{% extends 'accounts/header.html' %}

{% block title %} Added to cart {% endblock title %}

{% block content %}

<h2 style="text-align: center">Added to shopping basket</h2>

<div>
{% for item in show_cart %}

   <li> {{item}}</li>
    <li> Quantity: {{item.qty}}</li>

{% endfor %}
</div>

<a href="{% url 'main_app:cart_view' %}"><button type="submit" >Go to transaction </button></a>
<a href="{% url 'main_app:auctions' %}"><button type="submit" > Back to product list </button></a>

{% endblock %}

main_app/templates/main_app/update_product.html
{% extends 'accounts/header.html' %}

{% block title %} Update product {% endblock title %}

{% block content %}


<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{update_form.as_p}}
    <input type="submit" value="Update">
</form>

{% for message in messages %}
{% if message %}
{{message}} <button type="button" onclick="history.back()"> Back to update form</button>
{% endif %}

{% endfor %}





{% endblock %}

main_app/templates/main_app/user_products.html
{% extends 'accounts/header.html' %}

{% block title %} Your products {% endblock title %}

{% block content %}

{% for prod in product %}

<ul style="list-style-type: none">
<li>
{{prod}}<a href="{% url 'main_app:update_product' prod.id %}"><button>Update product details</button></a>
        <a href="{% url 'main_app:delete_product' prod.id %}"><button>Delete product</button></a>
</li>
{% endfor %}
</ul>
{% endblock %}