Drugie_życie_gabarytów/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')),
    path('accounts/', include('accounts.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/urls.py
from django.urls import path

from accounts import views

app_name = 'accounts'

urlpatterns = [

    path('register/', views.register_request, name='register'),
    path('login/', views.login_request, name='login'),
    # path('user_view/', views.user_view, name='user_view'),
    path('logout/', views.logout_request, name='logout'),

]

main_app/urls.py
from django.urls import path

from main_app import views

app_name = 'main_app'

urlpatterns = [
    path('', views.home, name='home'),
    path('about_us/', views.about_us, name='about_us'),

    # PRODUCT
    path('auctions/', views.auction_view, name='auctions'),
    path('<int:pk>/', views.product_detail_view, name='product_detail_view'),
    path('add/', views.add_product, name='add'),
    path('search/', views.search_by_name, name='search'),

    # USER
    path('user_products/', views.users_products, name='user_products'),
    path('update_product/<int:pk>/', views.update_product, name='update_product'),
    path('delete/<int:pk>/', views.delete_product, name='delete_product'),

    # CART
    path('cart/<int:pk>/', views.add_to_shopping_cart, name='add_to_shopping_cart'),
    path('cart_view/', views.cart_view, name='cart_view'),
    path('order_complete/', views.buy_now, name='order_complete'),
    path('remove/<int:pk>/', views.cart_remove, name='cart_remove'),
    path('update_cart/<int:pk>/', views.update_cart, name='update_cart'),

    #ORDER_VIEW
    path('orders/', views.orders, name='orders'),

]

accounts/models.py
from django.db import models

# Create your models here.

accounts/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model

User = get_user_model()


class CreateUserForm(UserCreationForm):
    class Meta:
        model = User
        fields = ("username", "email", "password1", "password2")

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login, authenticate, logout, get_user_model
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from .forms import CreateUserForm

User = get_user_model()


def register_request(request):
    form = CreateUserForm()
    if request.method == 'POST':
        form = CreateUserForm(request.POST)
        if form.is_valid():
            form.save()
            user = form.cleaned_data.get('username')
            messages.success(request, f'Account was created for {user}')
            return redirect('accounts:login')

    return render(request, 'accounts/register.html', context={'register_form': form})


def login_request(request):
    if request.method == "POST":
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(request, username=username, password=password)

        if user is not None:
            login(request, user)
            return redirect('main_app:auctions')
        else:
            messages.info(request, 'Wrong username or password')

    return render(request, 'accounts/login.html')


def logout_request(request):
    logout(request)
    return redirect('main_app:home')

accounts/templates/accounts/header.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    {% load static %}
    <link rel="stylesheet" href="{% static 'main_app/css/main.css'%}">
    <title> {% block title %} {% endblock title%} </title>
</head>
<body>
    <nav>
        <ul class="navigation-box">
            <div class="navigation">
                <div class="home"><a href="{% url 'main_app:home' %}">Home</a></div>
                <div class="auctions_view"><a href="{% url 'main_app:auctions' %}">Auctions</a></div>
                <div class="about-us"><a href="{% url 'main_app:about_us' %}">About us</a></div>
                <div class="contact"><a href="#">Contact</a></div>

                <div class="cart_view"><a href="{% url 'main_app:cart_view' %}">Shopping cart</a></div>
            </div>
        </ul>
    </nav>
<!--<script src="./main_app/js/script.js"></script>-->

    {% block content%}

    {% endblock %}

</body>
</html>

accounts/templates/accounts/login.html
<!DOCTYPE html>
<html lang="en">
{% extends 'accounts/header.html' %}

{% block title %} Log in {% endblock title %}

{% block content %}
<body>
<div class="form-structor">
    <div class="login">
        <h1 class="form-title" id="login">Log in</h1>
        <div class="form-holder">
            <form method="POST">
                {% csrf_token %}
                <input type="text" class="input" name="username" placeholder="Username">
                <input type="password" class="input" name="password" placeholder="Password">
                <button class="submit-btn"> Login </button>
            </form>
        </div>
    </div>
</div>
<div class="wrong-login">
{% for message in messages %}
            <p>{{message}}</p>
        {% endfor %}
</div>
</body>

{% endblock %}
</html>

accounts/templates/accounts/register.html
{% extends 'accounts/header.html' %}

{% block title %} Registration {% endblock title %}

{% block content %}
<body>
<style>
    .special_form{
        text-align: left;
        margin: 1cm;
    }
</style>
<div>
    <div>
        <h2>Sign up</h2>
    </div>
    <div>
        <form method="POST" class="special_form">
        {% csrf_token %}
        {{register_form}}
            <input type="submit" name="Create User">
            {{register_form.errors}}
        </form>
        <div class="login-question">
              <p>Already have an account?</p>
              <a class="login" href="{% url 'accounts:login' %}">
                  <button type="submit">Log in</button>
              </a>
        </div>
    </div>
</div>
{% endblock %}
</body>